package main

import (
	"fmt"
	"os"
	"os/exec"
	"path"
	"text/template"

	"github.com/gomlx/stablehlo/internal/utils"
	"github.com/gomlx/stablehlo/shapeinference"
	"github.com/janpfeifer/must"
)

const (
	unaryOpsFile = "gen_unary_ops.go"
)

var (
	unaryOpsTemplate = template.Must(
		template.
			New(unaryOpsFile).
			Parse(
				`/***** File generated by ./internal/cmd/ops_generator. Don't edit it directly. *****/

package stablehlo

import (
	"github.com/gomlx/stablehlo/internal/optypes"
)

{{- range .}}
// {{.Name}} implements the corresponding standard unary operation.
func {{.Name}}(operand *Value) (*Value, error) {
	fn := operand.fn
	return fn.unaryOp(optypes.{{.Name}}, operand)
}
{{- end}}
`))
)

type UnaryOp struct {
	Name string
}

func GenerateUnaryOps() {
	unaryOps := shapeinference.StandardUnaryOperations
	data := make([]UnaryOp, 0, len(unaryOps))

	for _, k := range utils.SortedKeys(unaryOps) {
		data = append(data, UnaryOp{Name: k.String()})
	}

	fileName := unaryOpsFile
	f := must.M1(os.Create(fileName))
	must.M(unaryOpsTemplate.Execute(f, data))
	must.M(f.Close())

	cmd := exec.Command("gofmt", "-w", fileName)
	must.M(cmd.Run())
	fmt.Printf("✅ Successfully generated %s\n", path.Join(must.M1(os.Getwd()), fileName))
}
