// Code generated by "enumer -type=OpType -output=gen_optype_enumer.go optypes.go"; DO NOT EDIT.

package optypes

import (
	"fmt"
	"strings"
)

const _OpTypeName = "InvalidFuncReturnConstantIdentityAbsAddAllReduceAndAtan2BatchNormInferenceBatchNormTrainingBatchNormGradBitcastConvertBroadcastInDimCbrtCeilClampCollectiveBroadcastCompareComplexConcatenateConvertConvolutionCosineCountLeadingZerosDivideDotGeneralDynamicSliceDynamicUpdateSliceErfExponentialExponentialMinusOneFftFloorGatherImagIsFiniteIotaLogLogPlusOneLogisticMaximumMinimumMultiplyNegateNotOrPadPopcntPowerRealRemainderReduceReduceWindowReshapeReverseRngBitGeneratorRoundNearestAfzRoundNearestEvenRsqrtScatterSelectSelectAndScatterShiftLeftShiftRightArithmeticShiftRightLogicalSignSineSliceSqrtSubtractTanTanhTransposeXorAllGatherAllToAllCaseCholeskyCollectivePermuteCompositeCustomCallDynamicBroadcastInDimDynamicConvDynamicGatherDynamicIotaDynamicPadDynamicReshapeGetDimensionSizeGetTupleElementIfInfeedOptimizationBarrierOutfeedPartitionIdRecvReducePrecisionReduceScatterSendTriangularSolveTupleUniformDequantizeUniformQuantizeWhileLast"

var _OpTypeIndex = [...]uint16{0, 7, 17, 25, 33, 36, 39, 48, 51, 56, 74, 91, 104, 118, 132, 136, 140, 145, 164, 171, 178, 189, 196, 207, 213, 230, 236, 246, 258, 276, 279, 290, 309, 312, 317, 323, 327, 335, 339, 342, 352, 360, 367, 374, 382, 388, 391, 393, 396, 402, 407, 411, 420, 426, 438, 445, 452, 467, 482, 498, 503, 510, 516, 532, 541, 561, 578, 582, 586, 591, 595, 603, 606, 610, 619, 622, 631, 639, 643, 651, 668, 677, 687, 708, 719, 732, 743, 753, 767, 783, 798, 800, 806, 825, 832, 843, 847, 862, 875, 879, 894, 899, 916, 931, 936, 940}

const _OpTypeLowerName = "invalidfuncreturnconstantidentityabsaddallreduceandatan2batchnorminferencebatchnormtrainingbatchnormgradbitcastconvertbroadcastindimcbrtceilclampcollectivebroadcastcomparecomplexconcatenateconvertconvolutioncosinecountleadingzerosdividedotgeneraldynamicslicedynamicupdatesliceerfexponentialexponentialminusonefftfloorgatherimagisfiniteiotaloglogplusonelogisticmaximumminimummultiplynegatenotorpadpopcntpowerrealremainderreducereducewindowreshapereverserngbitgeneratorroundnearestafzroundnearestevenrsqrtscatterselectselectandscattershiftleftshiftrightarithmeticshiftrightlogicalsignsineslicesqrtsubtracttantanhtransposexorallgatheralltoallcasecholeskycollectivepermutecompositecustomcalldynamicbroadcastindimdynamicconvdynamicgatherdynamiciotadynamicpaddynamicreshapegetdimensionsizegettupleelementifinfeedoptimizationbarrieroutfeedpartitionidrecvreduceprecisionreducescattersendtriangularsolvetupleuniformdequantizeuniformquantizewhilelast"

func (i OpType) String() string {
	if i < 0 || i >= OpType(len(_OpTypeIndex)-1) {
		return fmt.Sprintf("OpType(%d)", i)
	}
	return _OpTypeName[_OpTypeIndex[i]:_OpTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _OpTypeNoOp() {
	var x [1]struct{}
	_ = x[Invalid-(0)]
	_ = x[FuncReturn-(1)]
	_ = x[Constant-(2)]
	_ = x[Identity-(3)]
	_ = x[Abs-(4)]
	_ = x[Add-(5)]
	_ = x[AllReduce-(6)]
	_ = x[And-(7)]
	_ = x[Atan2-(8)]
	_ = x[BatchNormInference-(9)]
	_ = x[BatchNormTraining-(10)]
	_ = x[BatchNormGrad-(11)]
	_ = x[BitcastConvert-(12)]
	_ = x[BroadcastInDim-(13)]
	_ = x[Cbrt-(14)]
	_ = x[Ceil-(15)]
	_ = x[Clamp-(16)]
	_ = x[CollectiveBroadcast-(17)]
	_ = x[Compare-(18)]
	_ = x[Complex-(19)]
	_ = x[Concatenate-(20)]
	_ = x[Convert-(21)]
	_ = x[Convolution-(22)]
	_ = x[Cosine-(23)]
	_ = x[CountLeadingZeros-(24)]
	_ = x[Divide-(25)]
	_ = x[DotGeneral-(26)]
	_ = x[DynamicSlice-(27)]
	_ = x[DynamicUpdateSlice-(28)]
	_ = x[Erf-(29)]
	_ = x[Exponential-(30)]
	_ = x[ExponentialMinusOne-(31)]
	_ = x[Fft-(32)]
	_ = x[Floor-(33)]
	_ = x[Gather-(34)]
	_ = x[Imag-(35)]
	_ = x[IsFinite-(36)]
	_ = x[Iota-(37)]
	_ = x[Log-(38)]
	_ = x[LogPlusOne-(39)]
	_ = x[Logistic-(40)]
	_ = x[Maximum-(41)]
	_ = x[Minimum-(42)]
	_ = x[Multiply-(43)]
	_ = x[Negate-(44)]
	_ = x[Not-(45)]
	_ = x[Or-(46)]
	_ = x[Pad-(47)]
	_ = x[Popcnt-(48)]
	_ = x[Power-(49)]
	_ = x[Real-(50)]
	_ = x[Remainder-(51)]
	_ = x[Reduce-(52)]
	_ = x[ReduceWindow-(53)]
	_ = x[Reshape-(54)]
	_ = x[Reverse-(55)]
	_ = x[RngBitGenerator-(56)]
	_ = x[RoundNearestAfz-(57)]
	_ = x[RoundNearestEven-(58)]
	_ = x[Rsqrt-(59)]
	_ = x[Scatter-(60)]
	_ = x[Select-(61)]
	_ = x[SelectAndScatter-(62)]
	_ = x[ShiftLeft-(63)]
	_ = x[ShiftRightArithmetic-(64)]
	_ = x[ShiftRightLogical-(65)]
	_ = x[Sign-(66)]
	_ = x[Sine-(67)]
	_ = x[Slice-(68)]
	_ = x[Sqrt-(69)]
	_ = x[Subtract-(70)]
	_ = x[Tan-(71)]
	_ = x[Tanh-(72)]
	_ = x[Transpose-(73)]
	_ = x[Xor-(74)]
	_ = x[AllGather-(75)]
	_ = x[AllToAll-(76)]
	_ = x[Case-(77)]
	_ = x[Cholesky-(78)]
	_ = x[CollectivePermute-(79)]
	_ = x[Composite-(80)]
	_ = x[CustomCall-(81)]
	_ = x[DynamicBroadcastInDim-(82)]
	_ = x[DynamicConv-(83)]
	_ = x[DynamicGather-(84)]
	_ = x[DynamicIota-(85)]
	_ = x[DynamicPad-(86)]
	_ = x[DynamicReshape-(87)]
	_ = x[GetDimensionSize-(88)]
	_ = x[GetTupleElement-(89)]
	_ = x[If-(90)]
	_ = x[Infeed-(91)]
	_ = x[OptimizationBarrier-(92)]
	_ = x[Outfeed-(93)]
	_ = x[PartitionId-(94)]
	_ = x[Recv-(95)]
	_ = x[ReducePrecision-(96)]
	_ = x[ReduceScatter-(97)]
	_ = x[Send-(98)]
	_ = x[TriangularSolve-(99)]
	_ = x[Tuple-(100)]
	_ = x[UniformDequantize-(101)]
	_ = x[UniformQuantize-(102)]
	_ = x[While-(103)]
	_ = x[Last-(104)]
}

var _OpTypeValues = []OpType{Invalid, FuncReturn, Constant, Identity, Abs, Add, AllReduce, And, Atan2, BatchNormInference, BatchNormTraining, BatchNormGrad, BitcastConvert, BroadcastInDim, Cbrt, Ceil, Clamp, CollectiveBroadcast, Compare, Complex, Concatenate, Convert, Convolution, Cosine, CountLeadingZeros, Divide, DotGeneral, DynamicSlice, DynamicUpdateSlice, Erf, Exponential, ExponentialMinusOne, Fft, Floor, Gather, Imag, IsFinite, Iota, Log, LogPlusOne, Logistic, Maximum, Minimum, Multiply, Negate, Not, Or, Pad, Popcnt, Power, Real, Remainder, Reduce, ReduceWindow, Reshape, Reverse, RngBitGenerator, RoundNearestAfz, RoundNearestEven, Rsqrt, Scatter, Select, SelectAndScatter, ShiftLeft, ShiftRightArithmetic, ShiftRightLogical, Sign, Sine, Slice, Sqrt, Subtract, Tan, Tanh, Transpose, Xor, AllGather, AllToAll, Case, Cholesky, CollectivePermute, Composite, CustomCall, DynamicBroadcastInDim, DynamicConv, DynamicGather, DynamicIota, DynamicPad, DynamicReshape, GetDimensionSize, GetTupleElement, If, Infeed, OptimizationBarrier, Outfeed, PartitionId, Recv, ReducePrecision, ReduceScatter, Send, TriangularSolve, Tuple, UniformDequantize, UniformQuantize, While, Last}

var _OpTypeNameToValueMap = map[string]OpType{
	_OpTypeName[0:7]:          Invalid,
	_OpTypeLowerName[0:7]:     Invalid,
	_OpTypeName[7:17]:         FuncReturn,
	_OpTypeLowerName[7:17]:    FuncReturn,
	_OpTypeName[17:25]:        Constant,
	_OpTypeLowerName[17:25]:   Constant,
	_OpTypeName[25:33]:        Identity,
	_OpTypeLowerName[25:33]:   Identity,
	_OpTypeName[33:36]:        Abs,
	_OpTypeLowerName[33:36]:   Abs,
	_OpTypeName[36:39]:        Add,
	_OpTypeLowerName[36:39]:   Add,
	_OpTypeName[39:48]:        AllReduce,
	_OpTypeLowerName[39:48]:   AllReduce,
	_OpTypeName[48:51]:        And,
	_OpTypeLowerName[48:51]:   And,
	_OpTypeName[51:56]:        Atan2,
	_OpTypeLowerName[51:56]:   Atan2,
	_OpTypeName[56:74]:        BatchNormInference,
	_OpTypeLowerName[56:74]:   BatchNormInference,
	_OpTypeName[74:91]:        BatchNormTraining,
	_OpTypeLowerName[74:91]:   BatchNormTraining,
	_OpTypeName[91:104]:       BatchNormGrad,
	_OpTypeLowerName[91:104]:  BatchNormGrad,
	_OpTypeName[104:118]:      BitcastConvert,
	_OpTypeLowerName[104:118]: BitcastConvert,
	_OpTypeName[118:132]:      BroadcastInDim,
	_OpTypeLowerName[118:132]: BroadcastInDim,
	_OpTypeName[132:136]:      Cbrt,
	_OpTypeLowerName[132:136]: Cbrt,
	_OpTypeName[136:140]:      Ceil,
	_OpTypeLowerName[136:140]: Ceil,
	_OpTypeName[140:145]:      Clamp,
	_OpTypeLowerName[140:145]: Clamp,
	_OpTypeName[145:164]:      CollectiveBroadcast,
	_OpTypeLowerName[145:164]: CollectiveBroadcast,
	_OpTypeName[164:171]:      Compare,
	_OpTypeLowerName[164:171]: Compare,
	_OpTypeName[171:178]:      Complex,
	_OpTypeLowerName[171:178]: Complex,
	_OpTypeName[178:189]:      Concatenate,
	_OpTypeLowerName[178:189]: Concatenate,
	_OpTypeName[189:196]:      Convert,
	_OpTypeLowerName[189:196]: Convert,
	_OpTypeName[196:207]:      Convolution,
	_OpTypeLowerName[196:207]: Convolution,
	_OpTypeName[207:213]:      Cosine,
	_OpTypeLowerName[207:213]: Cosine,
	_OpTypeName[213:230]:      CountLeadingZeros,
	_OpTypeLowerName[213:230]: CountLeadingZeros,
	_OpTypeName[230:236]:      Divide,
	_OpTypeLowerName[230:236]: Divide,
	_OpTypeName[236:246]:      DotGeneral,
	_OpTypeLowerName[236:246]: DotGeneral,
	_OpTypeName[246:258]:      DynamicSlice,
	_OpTypeLowerName[246:258]: DynamicSlice,
	_OpTypeName[258:276]:      DynamicUpdateSlice,
	_OpTypeLowerName[258:276]: DynamicUpdateSlice,
	_OpTypeName[276:279]:      Erf,
	_OpTypeLowerName[276:279]: Erf,
	_OpTypeName[279:290]:      Exponential,
	_OpTypeLowerName[279:290]: Exponential,
	_OpTypeName[290:309]:      ExponentialMinusOne,
	_OpTypeLowerName[290:309]: ExponentialMinusOne,
	_OpTypeName[309:312]:      Fft,
	_OpTypeLowerName[309:312]: Fft,
	_OpTypeName[312:317]:      Floor,
	_OpTypeLowerName[312:317]: Floor,
	_OpTypeName[317:323]:      Gather,
	_OpTypeLowerName[317:323]: Gather,
	_OpTypeName[323:327]:      Imag,
	_OpTypeLowerName[323:327]: Imag,
	_OpTypeName[327:335]:      IsFinite,
	_OpTypeLowerName[327:335]: IsFinite,
	_OpTypeName[335:339]:      Iota,
	_OpTypeLowerName[335:339]: Iota,
	_OpTypeName[339:342]:      Log,
	_OpTypeLowerName[339:342]: Log,
	_OpTypeName[342:352]:      LogPlusOne,
	_OpTypeLowerName[342:352]: LogPlusOne,
	_OpTypeName[352:360]:      Logistic,
	_OpTypeLowerName[352:360]: Logistic,
	_OpTypeName[360:367]:      Maximum,
	_OpTypeLowerName[360:367]: Maximum,
	_OpTypeName[367:374]:      Minimum,
	_OpTypeLowerName[367:374]: Minimum,
	_OpTypeName[374:382]:      Multiply,
	_OpTypeLowerName[374:382]: Multiply,
	_OpTypeName[382:388]:      Negate,
	_OpTypeLowerName[382:388]: Negate,
	_OpTypeName[388:391]:      Not,
	_OpTypeLowerName[388:391]: Not,
	_OpTypeName[391:393]:      Or,
	_OpTypeLowerName[391:393]: Or,
	_OpTypeName[393:396]:      Pad,
	_OpTypeLowerName[393:396]: Pad,
	_OpTypeName[396:402]:      Popcnt,
	_OpTypeLowerName[396:402]: Popcnt,
	_OpTypeName[402:407]:      Power,
	_OpTypeLowerName[402:407]: Power,
	_OpTypeName[407:411]:      Real,
	_OpTypeLowerName[407:411]: Real,
	_OpTypeName[411:420]:      Remainder,
	_OpTypeLowerName[411:420]: Remainder,
	_OpTypeName[420:426]:      Reduce,
	_OpTypeLowerName[420:426]: Reduce,
	_OpTypeName[426:438]:      ReduceWindow,
	_OpTypeLowerName[426:438]: ReduceWindow,
	_OpTypeName[438:445]:      Reshape,
	_OpTypeLowerName[438:445]: Reshape,
	_OpTypeName[445:452]:      Reverse,
	_OpTypeLowerName[445:452]: Reverse,
	_OpTypeName[452:467]:      RngBitGenerator,
	_OpTypeLowerName[452:467]: RngBitGenerator,
	_OpTypeName[467:482]:      RoundNearestAfz,
	_OpTypeLowerName[467:482]: RoundNearestAfz,
	_OpTypeName[482:498]:      RoundNearestEven,
	_OpTypeLowerName[482:498]: RoundNearestEven,
	_OpTypeName[498:503]:      Rsqrt,
	_OpTypeLowerName[498:503]: Rsqrt,
	_OpTypeName[503:510]:      Scatter,
	_OpTypeLowerName[503:510]: Scatter,
	_OpTypeName[510:516]:      Select,
	_OpTypeLowerName[510:516]: Select,
	_OpTypeName[516:532]:      SelectAndScatter,
	_OpTypeLowerName[516:532]: SelectAndScatter,
	_OpTypeName[532:541]:      ShiftLeft,
	_OpTypeLowerName[532:541]: ShiftLeft,
	_OpTypeName[541:561]:      ShiftRightArithmetic,
	_OpTypeLowerName[541:561]: ShiftRightArithmetic,
	_OpTypeName[561:578]:      ShiftRightLogical,
	_OpTypeLowerName[561:578]: ShiftRightLogical,
	_OpTypeName[578:582]:      Sign,
	_OpTypeLowerName[578:582]: Sign,
	_OpTypeName[582:586]:      Sine,
	_OpTypeLowerName[582:586]: Sine,
	_OpTypeName[586:591]:      Slice,
	_OpTypeLowerName[586:591]: Slice,
	_OpTypeName[591:595]:      Sqrt,
	_OpTypeLowerName[591:595]: Sqrt,
	_OpTypeName[595:603]:      Subtract,
	_OpTypeLowerName[595:603]: Subtract,
	_OpTypeName[603:606]:      Tan,
	_OpTypeLowerName[603:606]: Tan,
	_OpTypeName[606:610]:      Tanh,
	_OpTypeLowerName[606:610]: Tanh,
	_OpTypeName[610:619]:      Transpose,
	_OpTypeLowerName[610:619]: Transpose,
	_OpTypeName[619:622]:      Xor,
	_OpTypeLowerName[619:622]: Xor,
	_OpTypeName[622:631]:      AllGather,
	_OpTypeLowerName[622:631]: AllGather,
	_OpTypeName[631:639]:      AllToAll,
	_OpTypeLowerName[631:639]: AllToAll,
	_OpTypeName[639:643]:      Case,
	_OpTypeLowerName[639:643]: Case,
	_OpTypeName[643:651]:      Cholesky,
	_OpTypeLowerName[643:651]: Cholesky,
	_OpTypeName[651:668]:      CollectivePermute,
	_OpTypeLowerName[651:668]: CollectivePermute,
	_OpTypeName[668:677]:      Composite,
	_OpTypeLowerName[668:677]: Composite,
	_OpTypeName[677:687]:      CustomCall,
	_OpTypeLowerName[677:687]: CustomCall,
	_OpTypeName[687:708]:      DynamicBroadcastInDim,
	_OpTypeLowerName[687:708]: DynamicBroadcastInDim,
	_OpTypeName[708:719]:      DynamicConv,
	_OpTypeLowerName[708:719]: DynamicConv,
	_OpTypeName[719:732]:      DynamicGather,
	_OpTypeLowerName[719:732]: DynamicGather,
	_OpTypeName[732:743]:      DynamicIota,
	_OpTypeLowerName[732:743]: DynamicIota,
	_OpTypeName[743:753]:      DynamicPad,
	_OpTypeLowerName[743:753]: DynamicPad,
	_OpTypeName[753:767]:      DynamicReshape,
	_OpTypeLowerName[753:767]: DynamicReshape,
	_OpTypeName[767:783]:      GetDimensionSize,
	_OpTypeLowerName[767:783]: GetDimensionSize,
	_OpTypeName[783:798]:      GetTupleElement,
	_OpTypeLowerName[783:798]: GetTupleElement,
	_OpTypeName[798:800]:      If,
	_OpTypeLowerName[798:800]: If,
	_OpTypeName[800:806]:      Infeed,
	_OpTypeLowerName[800:806]: Infeed,
	_OpTypeName[806:825]:      OptimizationBarrier,
	_OpTypeLowerName[806:825]: OptimizationBarrier,
	_OpTypeName[825:832]:      Outfeed,
	_OpTypeLowerName[825:832]: Outfeed,
	_OpTypeName[832:843]:      PartitionId,
	_OpTypeLowerName[832:843]: PartitionId,
	_OpTypeName[843:847]:      Recv,
	_OpTypeLowerName[843:847]: Recv,
	_OpTypeName[847:862]:      ReducePrecision,
	_OpTypeLowerName[847:862]: ReducePrecision,
	_OpTypeName[862:875]:      ReduceScatter,
	_OpTypeLowerName[862:875]: ReduceScatter,
	_OpTypeName[875:879]:      Send,
	_OpTypeLowerName[875:879]: Send,
	_OpTypeName[879:894]:      TriangularSolve,
	_OpTypeLowerName[879:894]: TriangularSolve,
	_OpTypeName[894:899]:      Tuple,
	_OpTypeLowerName[894:899]: Tuple,
	_OpTypeName[899:916]:      UniformDequantize,
	_OpTypeLowerName[899:916]: UniformDequantize,
	_OpTypeName[916:931]:      UniformQuantize,
	_OpTypeLowerName[916:931]: UniformQuantize,
	_OpTypeName[931:936]:      While,
	_OpTypeLowerName[931:936]: While,
	_OpTypeName[936:940]:      Last,
	_OpTypeLowerName[936:940]: Last,
}

var _OpTypeNames = []string{
	_OpTypeName[0:7],
	_OpTypeName[7:17],
	_OpTypeName[17:25],
	_OpTypeName[25:33],
	_OpTypeName[33:36],
	_OpTypeName[36:39],
	_OpTypeName[39:48],
	_OpTypeName[48:51],
	_OpTypeName[51:56],
	_OpTypeName[56:74],
	_OpTypeName[74:91],
	_OpTypeName[91:104],
	_OpTypeName[104:118],
	_OpTypeName[118:132],
	_OpTypeName[132:136],
	_OpTypeName[136:140],
	_OpTypeName[140:145],
	_OpTypeName[145:164],
	_OpTypeName[164:171],
	_OpTypeName[171:178],
	_OpTypeName[178:189],
	_OpTypeName[189:196],
	_OpTypeName[196:207],
	_OpTypeName[207:213],
	_OpTypeName[213:230],
	_OpTypeName[230:236],
	_OpTypeName[236:246],
	_OpTypeName[246:258],
	_OpTypeName[258:276],
	_OpTypeName[276:279],
	_OpTypeName[279:290],
	_OpTypeName[290:309],
	_OpTypeName[309:312],
	_OpTypeName[312:317],
	_OpTypeName[317:323],
	_OpTypeName[323:327],
	_OpTypeName[327:335],
	_OpTypeName[335:339],
	_OpTypeName[339:342],
	_OpTypeName[342:352],
	_OpTypeName[352:360],
	_OpTypeName[360:367],
	_OpTypeName[367:374],
	_OpTypeName[374:382],
	_OpTypeName[382:388],
	_OpTypeName[388:391],
	_OpTypeName[391:393],
	_OpTypeName[393:396],
	_OpTypeName[396:402],
	_OpTypeName[402:407],
	_OpTypeName[407:411],
	_OpTypeName[411:420],
	_OpTypeName[420:426],
	_OpTypeName[426:438],
	_OpTypeName[438:445],
	_OpTypeName[445:452],
	_OpTypeName[452:467],
	_OpTypeName[467:482],
	_OpTypeName[482:498],
	_OpTypeName[498:503],
	_OpTypeName[503:510],
	_OpTypeName[510:516],
	_OpTypeName[516:532],
	_OpTypeName[532:541],
	_OpTypeName[541:561],
	_OpTypeName[561:578],
	_OpTypeName[578:582],
	_OpTypeName[582:586],
	_OpTypeName[586:591],
	_OpTypeName[591:595],
	_OpTypeName[595:603],
	_OpTypeName[603:606],
	_OpTypeName[606:610],
	_OpTypeName[610:619],
	_OpTypeName[619:622],
	_OpTypeName[622:631],
	_OpTypeName[631:639],
	_OpTypeName[639:643],
	_OpTypeName[643:651],
	_OpTypeName[651:668],
	_OpTypeName[668:677],
	_OpTypeName[677:687],
	_OpTypeName[687:708],
	_OpTypeName[708:719],
	_OpTypeName[719:732],
	_OpTypeName[732:743],
	_OpTypeName[743:753],
	_OpTypeName[753:767],
	_OpTypeName[767:783],
	_OpTypeName[783:798],
	_OpTypeName[798:800],
	_OpTypeName[800:806],
	_OpTypeName[806:825],
	_OpTypeName[825:832],
	_OpTypeName[832:843],
	_OpTypeName[843:847],
	_OpTypeName[847:862],
	_OpTypeName[862:875],
	_OpTypeName[875:879],
	_OpTypeName[879:894],
	_OpTypeName[894:899],
	_OpTypeName[899:916],
	_OpTypeName[916:931],
	_OpTypeName[931:936],
	_OpTypeName[936:940],
}

// OpTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func OpTypeString(s string) (OpType, error) {
	if val, ok := _OpTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _OpTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to OpType values", s)
}

// OpTypeValues returns all values of the enum
func OpTypeValues() []OpType {
	return _OpTypeValues
}

// OpTypeStrings returns a slice of all String values of the enum
func OpTypeStrings() []string {
	strs := make([]string, len(_OpTypeNames))
	copy(strs, _OpTypeNames)
	return strs
}

// IsAOpType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i OpType) IsAOpType() bool {
	for _, v := range _OpTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
